name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Server
      run: cd server && cargo build --verbose
    - name: Run Server Tests
      run: cd server && ./scripts/init_db.sh && cargo test --verbose
    - name: Build CLI
      run: cd cli && cargo build --verbose
    - name: CLI Tests
      run: cd cli && cargo test --verbose
